server:
  port: 8888
spring:
  profiles:
    active: github
  cloud:
    config:
      server:
        git:
          uri:
          search-paths: respo
          username: liuixun@126.com
          password: github900126
      label: master
  application:
    name: xunconfig
logging:
  config: classpath:logback.xml